name: Tag with Proj Version
author: Rob Mayo (@waldosax)
description: Auto tags git with the version specified in a Visual Studio project file.

inputs:
    PROJECT_FILE_PATH:
        description: Filepath of the project to be packaged, relative to root of repository
        required: true
    VERSION_REGEX:
        description: Regex pattern to extract version info in a capturing group
        required: false
        default: ^\s*<Version>(.*)<\/Version>\s*$
    TAG_FORMAT:
        description: Format of the git tag, [*] gets replaced with actual version
        required: false
        default: v*

outputs:
    VERSION:
        description: Version of the associated git tag

runs:
    using: node12
    main: index.js

branding:
    icon: package
    color: blue